Redesign shop api (PLEASE TEST AND REVIEW)
AY2223S2-CS2103-W17-4/tp pull request #150
Opened 2023-04-06 07:45 UTC by ginloy

### MASSIVE API CHANGE
### Purpose
- Separate backend logic from parsing and command classes (Minimize number of classes to debug)
- Automate everything via one class (Cascading edits/deletes, adding, relations between entities)
- Isolate backend bugs to a single class
### How it works
- Shop now has methods to add, delete, modify etc
- Methods will handle all checks, cascading effects, error messages
- Ideally it cannot throw unchecked exceptions
- Any modifications to shop and its entities should be done through the API (viewing is ok)

2023-04-06 15:01 UTC, kimberlybp requested changes
Remember to remove unused/deprecated classes if this PR removes them (e.g. UniqueList)

2023-04-06 15:13 UTC, junlee1991 commented on src/test/java/seedu/address/logic/commands/UndoCommandTest.java
my test got commented out :(

2023-04-06 15:15 UTC, junlee1991 commented on src/main/java/seedu/address/model/entity/shop/exception/InsufficientPartException.java
My test got commented out :(

2023-04-06 15:24 UTC, ginloy commented on src/main/java/seedu/address/model/entity/shop/Shop.java
> +        return this.vehicles.stream().anyMatch(v -> v.getId() == id);
Theoretically it is impossible to add a duplicate plate number unless you extract the the customer out from the filtered list or you abuse `resetData() || overrideData()`. This method is needed for `viewX` which doesn't have access to attributes other than id and the jsonStorage methods which the user should not be able to call.

2023-04-06 15:24 UTC, ginloy commented on src/main/java/seedu/address/model/entity/shop/Shop.java
> +        return this.customers.stream().anyMatch(c -> c.getId() == id);
see above

2023-04-06 15:31 UTC, ginloy commented on src/main/java/seedu/address/storage/JsonSerializableShop.java
> +        List<Customer> customerLst = new ArrayList<>();
fixed

2023-04-06 15:32 UTC, ginloy commented on src/main/java/seedu/address/ui/ServiceDetailsPanel.java
> +        var partsRequired = service.getRequiredParts();
fixed

2023-04-06 15:33 UTC, ginloy commented on src/main/java/seedu/address/model/entity/shop/Shop.java
> +    public void overrideData(ObservableList<Customer> customers,
refactored

2023-04-06 15:36 UTC, ginloy commented on src/main/java/seedu/address/logic/commands/AddServiceCommand.java
> +            model.selectService(lst -> lst.get(lst.size() - 1));
I kinda lazy change now might change later

2023-04-06 15:50 UTC, kimberlybp commented on src/main/java/seedu/address/model/entity/shop/Shop.java
> +        return this.vehicles.stream().anyMatch(v -> v.getId() == id);
yea i think the og code had 2 hasVehicle methods also 1 to compare id and another 1 to compare Vehicles which would then compare car plate numbers

![image](https://user-images.githubusercontent.com/56817540/230431427-959e881c-b9f0-409b-b61b-ce8443ec1bf2.png)

iirc the one that compares car plate numbers is the validation for addVehicle command

2023-04-06 15:51 UTC, kimberlybp commented on src/main/java/seedu/address/model/entity/shop/exception/InsufficientPartException.java
probably need to update/fix according to the shop updates :'')

2023-04-07 09:21 UTC, ginloy commented
### Fix undo/redo
- Shifted logic (undo/redo stacks) over to Shop
- Added DeepCopy interface to ensure everything is deeply copied
- Got rid of some unused files
- Note: @kimberlybp I think there's still the bug where the panels attempt to update before maps and selected is updated when I undo but its still works so

2023-04-07 11:05 UTC, merged